site_name: Allfeat Documentation
site_url: https://docs.allfeat.com
site_description: A comprehensive guide for using and contributing to Allfeat.
site_author: Allfeat labs.

theme:
  name: material
  logo: assets/logos/allfeat-light.svg
  font: false
  favicon: https://www.allfeat.com/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: Allfeat
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: Allfeat-dark
      primary: custom
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: en

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.allfeat.com/
      name: Allfeat on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/Allfeat/
      name: Allfeat Github
    - icon: fontawesome/brands/linkedin
      link: https://fr.linkedin.com/company/allfeatlab
      name: Allfeat labs
  generator: false

copyright: Copyright &copy; 2023 - 2024 Allfeat

docs_dir: docs

nav:
  - Introduction: 'index.md'
  - Specific Features:
    - Overview: 'features/overview.md'
    - MIDDS:
      - MIDDS Overview: 'features/midds.md'
      - Artist Profiles: 'features/artists.md'
  - Networks:
    - Harmonie Testnet: 'networks/harmonie.md'
  - Technical Prerequisites: 'prerequisites.md'
  - Installation and Configuration:
    - Docker: 'installation/docker.md'
    - From Source:
      - Overview: 'installation/from-source.md'
      - Linux: 'installation/linux.md'
      - macOS: 'installation/macos.md'
      - Building: 'installation/build-allfeat.md'
  - Running a Local Node:
    - With Docker: 'running-a-node/docker.md'
    - Without Docker: 'running-a-node/without-docker.md'
  - Smart Contracts (DAPPs):
    - Developing: 'smart-contracts/developing.md'
    - MIDDS Integration: 'smart-contracts/midds-dapps.md'
  - Administering a Validator Node:
    - Prerequisites: 'validator-node/prerequisites.md'
    - Running as a Validator: 'validator-node/running-as-validator.md'
  - Compatible Wallets: 'wallets.md'
  - FAQ: 'faq.md'
  - Additional Resources: 'additional-resources.md'
  - Contributing to Allfeat: 'contributing.md'

plugins:
  - search
  - minify:
      minify_html: true
