site_name: Allfeat Documentation
site_url: https://docs.allfeat.com
site_description: A comprehensive guide for using and contributing to Allfeat.
site_author: Allfeat labs.

theme:
  name: material
  font:
    text: 'TasaOrbiter'
    url: 'assets/fonts/tasaOrbiter.woff2'
  logo: assets/logos/allfeat-light.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: Allfeat
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: Allfeat-dark
      primary: custom
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: en
extra_css:
  - stylesheets/extra.css

docs_dir: docs

nav:
  - Introduction: 'index.md'
  - Prerequisites: 'prerequisites.md'
  - Installation and Configuration:
    - Docker: 'installation/docker.md'
    - From Source: 'installation/from-source.md'
  - Running a Local Node:
    - With Docker: 'running-a-node/docker.md'
    - Without Docker: 'running-a-node/without-docker.md'
  - Smart Contracts (DAPPs):
    - Developing: 'smart-contracts/developing.md'
    - Deployment: 'smart-contracts/deployment.md'
  - Administering a Validator Node:
    - Prerequisites: 'validator-node/prerequisites.md'
    - Running as a Validator: 'validator-node/running-as-validator.md'
  - FAQ: 'faq.md'
  - Additional Resources: 'additional-resources.md'
  - Contributing to Allfeat: 'contributing.md'

plugins:
  - search
  - minify:
      minify_html: true
